config/routes.rb
Rails.application.routes.draw do
    root to: 'pages#home'
    get 'gallery', to: 'pages#gallery'
    get 'about', to: 'pages#about'
    get 'blog', to: 'pages#blog'
    get 'contact', to: 'pages#contact'
    resources :contacts
    get 'contacts/new', to: 'contacts#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
validates :name, presence:true
validates :email, presence:true
validates :comments, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
def new
    @contact =Contact.new
end


def create
    @contact = Contact.new(contact_params)
    if @contact.save
        redirect_to new_contact_path, notice: "Message sent."
    else
        redirect_to new_contact_path, notice: "Error occured."
    end
end
private 
    def contact_params
        params.require(:contact).permit(:name, :email, :comments)
     end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    
    def gallery
    end
    
    def about
    end
    
    def blog
    end
    
    def contact
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
  <div class="row">
    <h3 class="text-center">Contact Me</h3>
    <div class="col-md-4 col-md-offset-4">
        <%= flash[:notice] %>
      <div class="well">
        <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
          <%= f.submit 'Submit', class: 'btn btn-default' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewGem</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=VT323" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bangers" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Bungee+Shade|Press+Start+2P|Unica+One" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <nav class="navbar navbar-default navbar-static-top container-fluid " role="navigation">
  <div class='container'>
    <div class="navbar-header"> 
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        </div>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
        <i class="fa fa-group"></i>
         Home
      <% end %>
      
       <%= link_to gallery_path, class:"navbar-brand" do %>
       <i class="fa fa-camera"></i>
       Gallery
       <% end %>
       
       <%= link_to about_path, class:"navbar-brand" do %>
       <i class="fa fa-eye"></i>
       About
       <% end %>
       
       
       <%= link_to blog_path, class:"navbar-brand" do %>
       <i class="fa fa-file-o"></i>
       Blog
       <% end %>
      
    </div>
    <div class="collapse navbar-collapse" id="main-nav-collapse">
        
    
       
      <div class="nav navbar-nav navbar-right">
        <%= link_to new_contact_path, class:"navbar-brand" do %>
          <i class="fa fa-floppy-o"></i>
          Contact
          <% end %>
        </div>
        </div>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
    
    <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about-callout text-center">
    <h1>About Page</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet facilisis libero eget ultricies. Sed eu scelerisque sapien. Integer nec dui rhoncus, ultricies erat in, accumsan sem. Donec sodales elementum tincidunt. Nam eleifend interdum vulputate. Nulla quam dui, efficitur ac libero a, pellentesque tincidunt eros. Donec non lacus et dui interdum vulputate quis sed augue. Phasellus vitae metus ex. Donec nec tempor lectus, at congue mi. Nullam fermentum enim ut neque ultricies molestie.
        Praesent augue ex, interdum vel vulputate vitae, feugiat sed neque. In porttitor augue eu diam vestibulum volutpat ac eget turpis. Praesent imperdiet ex a magna sagittis, vel posuere justo eleifend. Sed nec est nec est euismod efficitur. Aliquam porta nec ex rutrum elementum. Nullam quis mauris in mi iaculis accumsan ut eu odio. Etiam sed justo a elit convallis semper. Aliquam feugiat diam euismod lectus vestibulum malesuada. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam malesuada rhoncus dapibus. Duis rutrum fringilla leo viverra faucibus. Nullam dictum quam nibh, at lacinia arcu iaculis eu. Curabitur commodo, metus non vehicula iaculis, tortor urna pharetra ante, vitae ultricies augue dui quis ligula. Cras turpis urna, consectetur quis tellus ut, aliquet luctus metus.
        Praesent condimentum leo nunc, in bibendum leo aliquam ac. Etiam porta sed magna id semper. Curabitur tincidunt malesuada felis sed lobortis. Phasellus sit amet lectus ut metus posuere cursus. Praesent commodo quis tortor non iaculis. Sed sollicitudin dolor quis sapien rutrum, ultricies gravida ex malesuada. Vestibulum ac egestas risus. Duis tincidunt augue in eros iaculis, sed dapibus sem placerat. Cras ac orci sem.
        
        Duis eleifend mi quis viverra ullamcorper. Mauris a purus porta, rhoncus tortor id, facilisis velit. Aenean iaculis, ex in imperdiet molestie, est nisl sagittis erat, auctor finibus magna sapien eget diam. Nam efficitur orci velit, iaculis porttitor nulla venenatis vitae. Donec tincidunt imperdiet tristique. Quisque pharetra, diam at luctus molestie, purus tellus cursus dolor, facilisis tempor sapien orci vitae purus. Donec ut felis eu massa accumsan faucibus at sed magna.
        Duis neque purus, posuere vel lorem nec, consequat rutrum ex. Nulla urna risus, sodales id nisl vitae, eleifend tincidunt justo. Integer nulla ligula, faucibus vel metus et, iaculis sodales nisi. In vehicula mollis est ultricies vulputate. Morbi ut aliquet sapien. Nam magna justo, maximus et suscipit a, tincidunt vitae metus. Vestibulum vel felis risus. Mauris porta felis sed pretium blandit. Nullam a metus in orci posuere tempus. Proin sed imperdiet enim, sed scelerisque nibh.

</p>
</div>

app/views/pages/blog.html.erb
<div class="blog-callout text-center container-fluid">
    <h1>Bl0gi ihqd44</h1>
    <h2>Blogitekstiii</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet facilisis libero eget ultricies. Sed eu scelerisque sapien. Integer nec dui rhoncus, ultricies erat in, accumsan sem. Donec sodales elementum tincidunt. Nam eleifend interdum vulputate. Nulla quam dui, efficitur ac libero a, pellentesque tincidunt eros. Donec non lacus et dui interdum vulputate quis sed augue. Phasellus vitae metus ex. Donec nec tempor lectus, at congue mi. Nullam fermentum enim ut neque ultricies molestie.
        Praesent augue ex, interdum vel vulputate vitae, feugiat sed neque. In porttitor augue eu diam vestibulum volutpat ac eget turpis. Praesent imperdiet ex a magna sagittis, vel posuere justo eleifend. Sed nec est nec est euismod efficitur. Aliquam porta nec ex rutrum elementum. Nullam quis mauris in mi iaculis accumsan ut eu odio. Etiam sed justo a elit convallis semper. Aliquam feugiat diam euismod lectus vestibulum malesuada. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam malesuada rhoncus dapibus. Duis rutrum fringilla leo viverra faucibus. Nullam dictum quam nibh, at lacinia arcu iaculis eu. Curabitur commodo, metus non vehicula iaculis, tortor urna pharetra ante, vitae ultricies augue dui quis ligula. Cras turpis urna, consectetur quis tellus ut, aliquet luctus metus.
        Praesent condimentum leo nunc, in bibendum leo aliquam ac. Etiam porta sed magna id semper. Curabitur tincidunt malesuada felis sed lobortis. Phasellus sit amet lectus ut metus posuere cursus. Praesent commodo quis tortor non iaculis. Sed sollicitudin dolor quis sapien rutrum, ultricies gravida ex malesuada. Vestibulum ac egestas risus. Duis tincidunt augue in eros iaculis, sed dapibus sem placerat. Cras ac orci sem.
        Duis eleifend mi quis viverra ullamcorper. Mauris a purus porta, rhoncus tortor id, facilisis velit. Aenean iaculis, ex in imperdiet molestie, est nisl sagittis erat, auctor finibus magna sapien eget diam. Nam efficitur orci velit, iaculis porttitor nulla venenatis vitae. Donec tincidunt imperdiet tristique. Quisque pharetra, diam at luctus molestie, purus tellus cursus dolor, facilisis tempor sapien orci vitae purus. Donec ut felis eu massa accumsan faucibus at sed magna.
        
        Duis neque purus, posuere vel lorem nec, consequat rutrum ex. Nulla urna risus, sodales id nisl vitae, eleifend tincidunt justo. Integer nulla ligula, faucibus vel metus et, iaculis sodales nisi. In vehicula mollis est ultricies vulputate. Morbi ut aliquet sapien. Nam magna justo, maximus et suscipit a, tincidunt vitae metus. Vestibulum vel felis risus. Mauris porta felis sed pretium blandit. Nullam a metus in orci posuere tempus. Proin sed imperdiet enim, sed scelerisque nibh.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet facilisis libero eget ultricies. Sed eu scelerisque sapien. Integer nec dui rhoncus, ultricies erat in, accumsan sem. Donec sodales elementum tincidunt. Nam eleifend interdum vulputate. Nulla quam dui, efficitur ac libero a, pellentesque tincidunt eros. Donec non lacus et dui interdum vulputate quis sed augue. Phasellus vitae metus ex. Donec nec tempor lectus, at congue mi. Nullam fermentum enim ut neque ultricies molestie.
        Praesent augue ex, interdum vel vulputate vitae, feugiat sed neque. In porttitor augue eu diam vestibulum volutpat ac eget turpis. Praesent imperdiet ex a magna sagittis, vel posuere justo eleifend. Sed nec est nec est euismod efficitur. Aliquam porta nec ex rutrum elementum. Nullam quis mauris in mi iaculis accumsan ut eu odio. Etiam sed justo a elit convallis semper. Aliquam feugiat diam euismod lectus vestibulum malesuada. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam malesuada rhoncus dapibus. Duis rutrum fringilla leo viverra faucibus. Nullam dictum quam nibh, at lacinia arcu iaculis eu. Curabitur commodo, metus non vehicula iaculis, tortor urna pharetra ante, vitae ultricies augue dui quis ligula. Cras turpis urna, consectetur quis tellus ut, aliquet luctus metus.
        Praesent condimentum leo nunc, in bibendum leo aliquam ac. Etiam porta sed magna id semper. Curabitur tincidunt malesuada felis sed lobortis. Phasellus sit amet lectus ut metus posuere cursus. Praesent commodo quis tortor non iaculis. Sed sollicitudin dolor quis sapien rutrum, ultricies gravida ex malesuada. Vestibulum ac egestas risus. Duis tincidunt augue in eros iaculis, sed dapibus sem placerat. Cras ac orci sem.
        
        Duis eleifend mi quis viverra ullamcorper. Mauris a purus porta, rhoncus tortor id, facilisis velit. Aenean iaculis, ex in imperdiet molestie, est nisl sagittis erat, auctor finibus magna sapien eget diam. Nam efficitur orci velit, iaculis porttitor nulla venenatis vitae. Donec tincidunt imperdiet tristique. Quisque pharetra, diam at luctus molestie, purus tellus cursus dolor, facilisis tempor sapien orci vitae purus. Donec ut felis eu massa accumsan faucibus at sed magna.
        Duis neque purus, posuere vel lorem nec, consequat rutrum ex. Nulla urna risus, sodales id nisl vitae, eleifend tincidunt justo. Integer nulla ligula, faucibus vel metus et, iaculis sodales nisi. In vehicula mollis est ultricies vulputate. Morbi ut aliquet sapien. Nam magna justo, maximus et suscipit a, tincidunt vitae metus. Vestibulum vel felis risus. Mauris porta felis sed pretium blandit. Nullam a metus in orci posuere tempus. Proin sed imperdiet enim, sed scelerisque nibh.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet facilisis libero eget ultricies. Sed eu scelerisque sapien. Integer nec dui rhoncus, ultricies erat in, accumsan sem. Donec sodales elementum tincidunt. Nam eleifend interdum vulputate. Nulla quam dui, efficitur ac libero a, pellentesque tincidunt eros. Donec non lacus et dui interdum vulputate quis sed augue. Phasellus vitae metus ex. Donec nec tempor lectus, at congue mi. Nullam fermentum enim ut neque ultricies molestie.
        Praesent augue ex, interdum vel vulputate vitae, feugiat sed neque. In porttitor augue eu diam vestibulum volutpat ac eget turpis. Praesent imperdiet ex a magna sagittis, vel posuere justo eleifend. Sed nec est nec est euismod efficitur. Aliquam porta nec ex rutrum elementum. Nullam quis mauris in mi iaculis accumsan ut eu odio. Etiam sed justo a elit convallis semper. Aliquam feugiat diam euismod lectus vestibulum malesuada. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam malesuada rhoncus dapibus. Duis rutrum fringilla leo viverra faucibus. Nullam dictum quam nibh, at lacinia arcu iaculis eu. Curabitur commodo, metus non vehicula iaculis, tortor urna pharetra ante, vitae ultricies augue dui quis ligula. Cras turpis urna, consectetur quis tellus ut, aliquet luctus metus.
        
        Praesent condimentum leo nunc, in bibendum leo aliquam ac. Etiam porta sed magna id semper. Curabitur tincidunt malesuada felis sed lobortis. Phasellus sit amet lectus ut metus posuere cursus. Praesent commodo quis tortor non iaculis. Sed sollicitudin dolor quis sapien rutrum, ultricies gravida ex malesuada. Vestibulum ac egestas risus. Duis tincidunt augue in eros iaculis, sed dapibus sem placerat. Cras ac orci sem.
        Duis eleifend mi quis viverra ullamcorper. Mauris a purus porta, rhoncus tortor id, facilisis velit. Aenean iaculis, ex in imperdiet molestie, est nisl sagittis erat, auctor finibus magna sapien eget diam. Nam efficitur orci velit, iaculis porttitor nulla venenatis vitae. Donec tincidunt imperdiet tristique. Quisque pharetra, diam at luctus molestie, purus tellus cursus dolor, facilisis tempor sapien orci vitae purus. Donec ut felis eu massa accumsan faucibus at sed magna.
        Duis neque purus, posuere vel lorem nec, consequat rutrum ex. Nulla urna risus, sodales id nisl vitae, eleifend tincidunt justo. Integer nulla ligula, faucibus vel metus et, iaculis sodales nisi. In vehicula mollis est ultricies vulputate. Morbi ut aliquet sapien. Nam magna justo, maximus et suscipit a, tincidunt vitae metus. Vestibulum vel felis risus. Mauris porta felis sed pretium blandit. Nullam a metus in orci posuere tempus. Proin sed imperdiet enim, sed scelerisque nibh.

    </p>
</div>

app/views/pages/contact.html.erb
<div class="contact-callout text-center container-fluid">
    <h1>Contact me!</h1>
    <h2>Info</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet facilisis libero eget ultricies. Sed eu scelerisque sapien. Integer nec dui rhoncus, ultricies erat in, accumsan sem. Donec sodales elementum tincidunt. Nam eleifend interdum vulputate. Nulla quam dui, efficitur ac libero a, pellentesque tincidunt eros. Donec non lacus et dui interdum vulputate quis sed augue. Phasellus vitae metus ex. Donec nec tempor lectus, at congue mi. Nullam fermentum enim ut neque ultricies molestie.
        Praesent augue ex, interdum vel vulputate vitae, feugiat sed neque. In porttitor augue eu diam vestibulum volutpat ac eget turpis. Praesent imperdiet ex a magna sagittis, vel posuere justo eleifend. Sed nec est nec est euismod efficitur. Aliquam porta nec ex rutrum elementum. Nullam quis mauris in mi iaculis accumsan ut eu odio. Etiam sed justo a elit convallis semper. Aliquam feugiat diam euismod lectus vestibulum malesuada. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam malesuada rhoncus dapibus. Duis rutrum fringilla leo viverra faucibus. Nullam dictum quam nibh, at lacinia arcu iaculis eu. Curabitur commodo, metus non vehicula iaculis, tortor urna pharetra ante, vitae ultricies augue dui quis ligula. Cras turpis urna, consectetur quis tellus ut, aliquet luctus metus.
        Praesent condimentum leo nunc, in bibendum leo aliquam ac. Etiam porta sed magna id semper. Curabitur tincidunt malesuada felis sed lobortis. Phasellus sit amet lectus ut metus posuere cursus. Praesent commodo quis tortor non iaculis. Sed sollicitudin dolor quis sapien rutrum, ultricies gravida ex malesuada. Vestibulum ac egestas risus. Duis tincidunt augue in eros iaculis, sed dapibus sem placerat. Cras ac orci sem.
        Duis eleifend mi quis viverra ullamcorper. Mauris a purus porta, rhoncus tortor id, facilisis velit. Aenean iaculis, ex in imperdiet molestie, est nisl sagittis erat, auctor finibus magna sapien eget diam. Nam efficitur orci velit, iaculis porttitor nulla venenatis vitae. Donec tincidunt imperdiet tristique. Quisque pharetra, diam at luctus molestie, purus tellus cursus dolor, facilisis tempor sapien orci vitae purus. Donec ut felis eu massa accumsan faucibus at sed magna.
        Duis neque purus, posuere vel lorem nec, consequat rutrum ex. Nulla urna risus, sodales id nisl vitae, eleifend tincidunt justo. Integer nulla ligula, faucibus vel metus et, iaculis sodales nisi. In vehicula mollis est ultricies vulputate. Morbi ut aliquet sapien. Nam magna justo, maximus et suscipit a, tincidunt vitae metus. Vestibulum vel felis risus. Mauris porta felis sed pretium blandit. Nullam a metus in orci posuere tempus. Proin sed imperdiet enim, sed scelerisque nibh.
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet facilisis libero eget ultricies. Sed eu scelerisque sapien. Integer nec dui rhoncus, ultricies erat in, accumsan sem. Donec sodales elementum tincidunt. Nam eleifend interdum vulputate. Nulla quam dui, efficitur ac libero a, pellentesque tincidunt eros. Donec non lacus et dui interdum vulputate quis sed augue. Phasellus vitae metus ex. Donec nec tempor lectus, at congue mi. Nullam fermentum enim ut neque ultricies molestie.
        Praesent augue ex, interdum vel vulputate vitae, feugiat sed neque. In porttitor augue eu diam vestibulum volutpat ac eget turpis. Praesent imperdiet ex a magna sagittis, vel posuere justo eleifend. Sed nec est nec est euismod efficitur. Aliquam porta nec ex rutrum elementum. Nullam quis mauris in mi iaculis accumsan ut eu odio. Etiam sed justo a elit convallis semper. Aliquam feugiat diam euismod lectus vestibulum malesuada. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam malesuada rhoncus dapibus. Duis rutrum fringilla leo viverra faucibus. Nullam dictum quam nibh, at lacinia arcu iaculis eu. Curabitur commodo, metus non vehicula iaculis, tortor urna pharetra ante, vitae ultricies augue dui quis ligula. Cras turpis urna, consectetur quis tellus ut, aliquet luctus metus.
        Praesent condimentum leo nunc, in bibendum leo aliquam ac. Etiam porta sed magna id semper. Curabitur tincidunt malesuada felis sed lobortis. Phasellus sit amet lectus ut metus posuere cursus. Praesent commodo quis tortor non iaculis. Sed sollicitudin dolor quis sapien rutrum, ultricies gravida ex malesuada. Vestibulum ac egestas risus. Duis tincidunt augue in eros iaculis, sed dapibus sem placerat. Cras ac orci sem.
        Duis eleifend mi quis viverra ullamcorper. Mauris a purus porta, rhoncus tortor id, facilisis velit. Aenean iaculis, ex in imperdiet molestie, est nisl sagittis erat, auctor finibus magna sapien eget diam. Nam efficitur orci velit, iaculis porttitor nulla venenatis vitae. Donec tincidunt imperdiet tristique. Quisque pharetra, diam at luctus molestie, purus tellus cursus dolor, facilisis tempor sapien orci vitae purus. Donec ut felis eu massa accumsan faucibus at sed magna.
        Duis neque purus, posuere vel lorem nec, consequat rutrum ex. Nulla urna risus, sodales id nisl vitae, eleifend tincidunt justo. Integer nulla ligula, faucibus vel metus et, iaculis sodales nisi. In vehicula mollis est ultricies vulputate. Morbi ut aliquet sapien. Nam magna justo, maximus et suscipit a, tincidunt vitae metus. Vestibulum vel felis risus. Mauris porta felis sed pretium blandit. Nullam a metus in orci posuere tempus. Proin sed imperdiet enim, sed scelerisque nibh.
    </p>
</div>

app/views/pages/gallery.html.erb
<div class="gallery-callout text-center container-fluid">
    <h1>Gallery</h1>
    <h2>Pictures</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse imperdiet facilisis libero eget ultricies. Sed eu scelerisque sapien. Integer nec dui rhoncus, ultricies erat in, accumsan sem. Donec sodales elementum tincidunt. Nam eleifend interdum vulputate. Nulla quam dui, efficitur ac libero a, pellentesque tincidunt eros. Donec non lacus et dui interdum vulputate quis sed augue. Phasellus vitae metus ex. Donec nec tempor lectus, at congue mi. Nullam fermentum enim ut neque ultricies molestie.
        Praesent augue ex, interdum vel vulputate vitae, feugiat sed neque. In porttitor augue eu diam vestibulum volutpat ac eget turpis. Praesent imperdiet ex a magna sagittis, vel posuere justo eleifend. Sed nec est nec est euismod efficitur. Aliquam porta nec ex rutrum elementum. Nullam quis mauris in mi iaculis accumsan ut eu odio. Etiam sed justo a elit convallis semper. Aliquam feugiat diam euismod lectus vestibulum malesuada. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam malesuada rhoncus dapibus. Duis rutrum fringilla leo viverra faucibus. Nullam dictum quam nibh, at lacinia arcu iaculis eu. Curabitur commodo, metus non vehicula iaculis, tortor urna pharetra ante, vitae ultricies augue dui quis ligula. Cras turpis urna, consectetur quis tellus ut, aliquet luctus metus.
        Praesent condimentum leo nunc, in bibendum leo aliquam ac. Etiam porta sed magna id semper. Curabitur tincidunt malesuada felis sed lobortis. Phasellus sit amet lectus ut metus posuere cursus. Praesent commodo quis tortor non iaculis. Sed sollicitudin dolor quis sapien rutrum, ultricies gravida ex malesuada. Vestibulum ac egestas risus. Duis tincidunt augue in eros iaculis, sed dapibus sem placerat. Cras ac orci sem.
        Duis eleifend mi quis viverra ullamcorper. Mauris a purus porta, rhoncus tortor id, facilisis velit. Aenean iaculis, ex in imperdiet molestie, est nisl sagittis erat, auctor finibus magna sapien eget diam. Nam efficitur orci velit, iaculis porttitor nulla venenatis vitae. Donec tincidunt imperdiet tristique. Quisque pharetra, diam at luctus molestie, purus tellus cursus dolor, facilisis tempor sapien orci vitae purus. Donec ut felis eu massa accumsan faucibus at sed magna.
        Duis neque purus, posuere vel lorem nec, consequat rutrum ex. Nulla urna risus, sodales id nisl vitae, eleifend tincidunt justo. Integer nulla ligula, faucibus vel metus et, iaculis sodales nisi. In vehicula mollis est ultricies vulputate. Morbi ut aliquet sapien. Nam magna justo, maximus et suscipit a, tincidunt vitae metus. Vestibulum vel felis risus. Mauris porta felis sed pretium blandit. Nullam a metus in orci posuere tempus. Proin sed imperdiet enim, sed scelerisque nibh.
    </p>
</div>